### ISSUE TITLE
"Could not create GL context" error on startup for GL 3.0

### ISSUE THREAD

**Issue by edward-san** [cristicbz/rust-doom#58] opened 2015-10-29 16:07 UTC
Since commit 65dbb735249badebce7298ba97a8490d2bc20506 , when I try to run rs_doom, compiled with nightly rustc (```1.6.0-nightly (8ca0acc25 2015-10-28)```), I get this message:

```
$ target/debug/rs_doom
rs_doom: graphics error: SDL: SDL error: Could not create GL context
```

I'm on Ubuntu 14.04 x86_64, running on this laptop with the following specs:

CPU: Intel Core i3-2328M
GPU: Intel Sandybridge Mobile

the mesa driver supports Opengl 3.0 and 3.1(core profile), if it might help.

**Comment by cristicbz** [comment] 2015-10-29 16:22
I was worried about this; I did a little compatibility survey on #rust-gamedev and it seemed fine though. I bumped the OpenGL requirement to 3.3, but I guess I shouldn't have. 

The reason I had to do this was because I'm using a `BUFFER_TEXTURE` instead of a uniform array in `static.vert` because glium doesn't support uniform arrays (they're slightly obsolete in a sense, thanks to uniform blocks and buffer textures).

I should try switching back to a uniform array with a glium workaround. I'll have a look tonight, sorry about the breakage! :(

**Comment by cristicbz** [comment] 2015-11-01 00:55
Hi @edward-san ! Sorry it took me a while to get to this; I merged #64 which (since you mention your drivers support 3.1 core), should make it work on your machine again. Could you please try and let me know? Thanks!

**Comment by edward-san** [comment] 2015-11-01 02:13
Yes, it opens fine, but the rendering is now different from before. See this screenshot:

![rust-doom_wrong_gamma](https://cloud.githubusercontent.com/assets/1041141/10866902/7556627e-8046-11e5-8d49-6de5de59dd24.png)

**Comment by cristicbz** [comment] 2015-11-01 09:59
Is the problem that `washed-out`-ness? Can't easily tell from the screenshot.

**Comment by cristicbz** [comment] 2015-11-01 10:06
Would you mind checking out the old version (say `git checkout 151b93a2d92c46aa8002edf69970dbe54c1f7637`) and send me a comparison screenshot, please?

**Comment by edward-san** [comment] 2015-11-01 22:08
Oops, sorry for that. Here:

![rust_doom_before_glium](https://cloud.githubusercontent.com/assets/1041141/10871665/7a15b66e-80ed-11e5-99f4-4ac3e28aef22.png)

**Comment by cristicbz** [comment] 2015-11-02 10:40
Thanks a lot @edward-san ! Good news is I managed to reproduce this by using my laptop's nvidia card instead of the integrated one. I'll try to find what's happening; working theory: BUFFER_TEXTURE is used to just store numbers, but it is a texture so sRGB correction hits somewhere where it didn't used to, muddling everything up.

**Comment by petevine** [comment] 2015-11-02 20:12
Is there a way to disable the shader stuff so it could be run on OpenGL 1.x?

This way it could even start working on arm devices using the glshim wrapper.

**Comment by cristicbz** [comment] 2015-11-02 20:44
@petevine In short, not easily: glium (the library used for OpenGL calls) doesn't support the fixed function pipeline and even if it did it's not clear that it would be easy to achieve all the effects needed using it. You're better off with a software renderer at that point. If you have some ideas or want to discuss this further, could you please file a different issue?

**Comment by cristicbz** [comment] 2015-11-02 20:47
Regarding this actual issue. Having investigated more, it seems to be entirely unrelated to the buffer texture thing: even just clearing the screen looks different. The bug is triggered only by running the glium version with the nvidia card. Switching to the pre-glium version of the code or to the integrated gpu both fix it.

New theory: something in the initialisation of glium messes with gamma/brightness somehow.

**Comment by cristicbz** [comment] 2015-11-02 22:32
OK so the issue was that if the device is SRGB capable, then glium assumes an SRGB framebuffer by default. I had to change everything to use SRGB everywhere and that seems to have fixed it on my nvidia card.

@edward-san Could you please check whether this works for you now?

**Comment by edward-san** [comment] 2015-11-03 01:31
@cristicbz yes, it fixed the issue.

**Comment by cristicbz** [comment] 2015-11-03 08:59
Yay, great, thanks for filing and being patient!

**Closed by cristicbz** 2015-11-03 08:59 UTC
Labels: compat
